Added migration and collectstatic commands to debian/postinst. [Merge] ~autonomouse/weebl:pkg/migrations_collectstatic_to_postinst into weebl:master

diff --git a/debian/python3-weebl.postinst b/debian/python3-weebl.postinst
--- a/debian/python3-weebl.postinst
+++ b/debian/python3-weebl.postinst
@@ -1,2 +1,7 @@
 rm -rf /etc/nginx/sites-enabled/weebl-nginx-site.conf
 ln -s /usr/share/weebl/weebl-nginx-site.conf /etc/nginx/sites-enabled/weebl-nginx-site.conf
+
+echo "Migrating database and collecting static files..."
+export DJANGO_SETTINGS_MODULE=weebl.settings
+/usr/bin/python3 /usr/bin/django-admin collectstatic --noinput
+/usr/bin/python3 /usr/bin/django-admin migrate --noinput || echo "Migration failed"
